### ISSUE TITLE
package-sets

### ISSUE THREAD

**Issue by jamesdbrock** [zapph/purescript-longs#2]
Hi zapph, I'm adding this package to package-sets, I hope you don't mind. Thanks for the package!

https://github.com/purescript/package-sets/pull/706

**Comment by jamesdbrock** [comment]
Actually, maybe I'm not adding it to package-sets, because I guess it has an undeclared dependency. Probably you didn't intend for the package itself to depend on QuickCheck.

https://github.com/purescript/package-sets/pull/706/checks?check_run_id=1158818459

```
[info] Verifying package "longs"
Error found:
in module Data.Long.Internal
at .spago/longs/v0.1.1/src/Data/Long/Internal.purs:54:1 - 54:52 (line 54, column 1 - line 54, column 52)

  Module Test.QuickCheck was not found.
```

**Comment by jamesdbrock** [comment]
Okay I added `quickcheck` to the package-sets dependency list for `longs`.

**Comment by jvliwanag** [comment]
Thanks for this. purescript-quickcheck should have been added as a dependency rather than a devDependency. I'll take care of that.

**Comment by jamesdbrock** [comment]
Thanks @jvliwanag . It probably goes without saying, but please feel free to move `longs` from `jamesbrock.dhall` into `zapph.dhall` in __package-sets__ any time you want.
